development:
  adapter: mysql2
  database: <%= app_name %>_dev
  encoding: utf8
  username: <%%= ENV['MYSQL_USER'] %>
  password: <%%= ENV['MYSQL_PASSWORD'] %>

test:
  adapter: mysql2
  database: <%= app_name %>_test
  username: <%%= ENV['MYSQL_USER'] %>
  password: <%%= ENV['MYSQL_PASSWORD'] %>

production:
  adapter: mysql2
  database: <%= app_name %>
  username: <%%= ENV['MYSQL_USER'] %>
  password: <%%= ENV['MYSQL_PASSWORD'] %>